### ISSUE TITLE
STL sheet 

### ISSUE THREAD

**Issue by Astro0mar** [7oSkaaa/Competitive-Programming-Session-Content#1]
The link of STL sheet on notion doesn't work

**Comment by 7oSkaaa** [comment]
Ok, Try now

**Comment by Astro0mar** [comment]
I think the new link is general and not related to STLs?

https://github.com/7oSkaaa/Competitive-Programming-Session-Content/blob/main/STLS%20Session/readme.md

**Comment by 7oSkaaa** [comment]
It's a sheet collected from codeforces to train on STLs

**Comment by Astro0mar** [comment]
Why I only see contests but not sheet? 😥

**Comment by 7oSkaaa** [comment]
The sheet like a contest you can enter and solve freely
